# FactionsBreakReloaded Configuration (made by iGniSsak)
tnt:
  radius: 1
  ignore_water: true
  ignore_lava: true
durability:
  obsidian: 5
  bedrock: 10
on_break_effect: "ENDER_SIGNAL"
info:
  item: "FEATHER"
  title: "&a&lDurability"
  sub-title: "&f%durability%"
messages:
  no-perm: "&cYou can't do this."
  reloaded: "&aConfiguration has been reloaded."