name: FactionsBreak
version: ${project.version}
main: cz.ignissak.fbr.Core
authors: [iGniSsak]
commands:
  factionsbreak:
    usage: /<command>
    aliases: [fb, factionsb]
    description: Main command for FactionsBreak
